name = "MajoranaBraiding"
uuid = "f83b5287-d29b-4393-86aa-12b1ba9ce9f2"
authors = ["Viktor Svensson <svensson.viktor.91@gmail.com> and Maximilian Nitsch"]
version = "1.2.0-DEV"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Majoranas = "c0bcf24a-0299-47db-9920-c7627388ccab"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuantumDots = "312194fd-fec5-4b07-ba1c-a40d7013a56a"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[sources]
Majoranas = {url = "https://github.com/williamesamuelson/Majoranas.jl"}
QuantumDots = {url = "https://github.com/cvsvensson/QuantumDots.jl"}

[compat]
Accessors = "0.1.38"
CairoMakie = "0.12.15"
OrdinaryDiffEqCore = "1.12.1"
OrdinaryDiffEqTsit5 = "1.1.0"
QuantumDots = "0.12"
SymPy = "2.2.0"
Symbolics = "6.21.0"
UnPack = "1.0.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
